# Generated by Django 3.0.5 on 2020-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200504_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Выбрать автора', to='catalog.Author'),
        ),
    ]
