# Generated by Django 3.0.5 on 2020-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200504_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выбрать автора', to='catalog.Author'),
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
